[profile.default]
src = "src"
test = "test"
out = "out"
libs = ["lib"]

solc_version = "0.8.28"
auto_detect_solc = false
auto_detect_remappings = false
evm_version = "cancun"

optimizer = true
optimizer_runs = 200

script = "scripts"

fs_permissions = [
    { access = "read", path = "./scripts/example_config.json" },
    { access = "read", path = "./config.json" },
    { access = "read", path = "./scripts/config.json" },
]

[fuzz]
runs = 256

[invariant]
runs = 256
depth = 500

[profile.lint]
exclude_lints = [
    "unaliased-plain-import",
    "mixed-case-function",
    "screaming-snake-case-const",
    "erc20-unchecked-transfer",
    "asm-keccak256",
    "mixed-case-variable",
]
